apiVersion: "v1"
protocol: "http"
address: ":80"
description: "Web Server LLM"
commands:
  - regex: "^.*$"
    plugin: "LLMHoneypot"
    statusCode: 200
plugin:
  llmProvider: ${LLM_PROVIDER}
  llmModel: ${LLM_MODEL}
  host: ${LLM_HOST}
  #openAISecretKey: ${OPEN_AI_SECRET_KEY}
